# Artificial Neural Network

### Importing the libraries

In [198]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, LabelEncoder, OrdinalEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

In [199]:
tf.__version__

'2.17.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [202]:
df = pd.read_csv("D:/BelajarMachineLearning/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv")
df.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [203]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [204]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [205]:
print(y)

[1 0 1 ... 1 1 0]


### Splitting the dataset into the Training set and Test set

In [207]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

### Preprocessing

In [209]:
ct = ColumnTransformer(
    transformers=[
        ("onehot", OneHotEncoder(drop="first"), [1,2]),
        ("ordinal", OrdinalEncoder(), [2]),
        ("num", StandardScaler(), [0,3,4,5,6,9])
    ],
    remainder="passthrough"
)

X_train = np.array(ct.fit_transform(X_train))
X_test = np.array(ct.transform(X_test))

In [210]:
print(X_test)

[[1.0 0.0 1.0 ... -1.019605111673559 0 0]
 [0.0 0.0 1.0 ... 0.7988829051630715 1 1]
 [0.0 1.0 0.0 ... -0.7279795338426726 1 0]
 ...
 [0.0 0.0 0.0 ... -1.1659158548265467 1 0]
 [0.0 0.0 1.0 ... -0.4116346313719027 1 0]
 [1.0 0.0 1.0 ... 0.12593183099572483 1 1]]


In [211]:
X_train = X_train.astype(np.float32)
X_test = X_test.astype(np.float32)

print(X_train.dtype)
print(X_test.dtype)

float32
float32


## Part 2 - Building the ANN

### Initializing the ANN

In [214]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [216]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu")) #rectifier

### Adding the second hidden layer

In [218]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu")) #rectifier

### Adding the output layer

In [220]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid")) #sigmoid

## Part 3 - Training the ANN

### Compiling the ANN

In [223]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [225]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7189 - loss: 0.6357
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8017 - loss: 0.4842
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8220 - loss: 0.4146
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8140 - loss: 0.4138
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8350 - loss: 0.3915
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8411 - loss: 0.3735
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8326 - loss: 0.3872
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8433 - loss: 0.3688
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8545 - loss: 0.3510
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8549 - loss: 0.3602
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8593 - loss: 0.3421
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [267]:
print(ann.predict((ct.transform([[600, "France", "Male", 40, 3, 60000, 2, 1, 1, 50000]])).astype(np.float32)) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[False]]


**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [275]:
y_pred = ann.predict(X_test.astype(np.float32))
y_pred = y_pred > 0.5

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


### Making the Confusion Matrix

In [277]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[1533   74]
 [ 201  192]]
0.8625
